name = "akamai"
type = "webpack"

account_id = "ca7271d81a89aa1b584684f4aea8c1a4"
workers_dev = true
compatibility_date = "2021-11-15"

[vars]
# This is your custom domain configured in Okta.
ORIGIN = "https://subway.atko.rocks"
# Get this value from your Upstash account.
UPSTASH_ENDPOINT = "https://eu1-artistic-bass-33019.upstash.io"
# Change this if you want to modify the TTL for stashed data.
UPSTASH_EXPIRE = 300
# Makes testing easier since the header is 'hardcoded'.
SCORE = 50

# [secrets]
# UPSTASH_TOKEN
